// <auto-generated />
namespace WAD_T2104E_Vũ_Đức_Thanh.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class thanhAbc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(thanhAbc));
        
        string IMigrationMetadata.Id
        {
            get { return "202209131354316_thanhAbc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
